// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gwcrkagqiepcbbmemnyz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd3Y3JrYWdxaWVwY2JibWVtbnl6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkxMzI4OTYsImV4cCI6MjA2NDcwODg5Nn0.xIG3PMc23Y0PamtZg2J6IuS6ZyE62W9aBa__4kfNPmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);